version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:3.2.0-alpine
  app:
    build: .
    command: /bin/bash -c 'script/start'
    volumes:
      - bundle:/bundle
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: password
      DB_HOST: mysql
      REDIS_HOST: redis
    links:
      - mysql
      - redis
volumes:
  data:
    driver: local
  bundle:
    driver: local
